// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTtZ1Z8dGX0nqg3fLFJRyXF4n_3yOpMIw',
    appId: '1:585764705287:web:d142f739a8ce479c3e06a2',
    messagingSenderId: '585764705287',
    projectId: 'flutterflix-375a9',
    authDomain: 'flutterflix-375a9.firebaseapp.com',
    storageBucket: 'flutterflix-375a9.appspot.com',
    measurementId: 'G-HT7M1PRT25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCidPh1H7wlkgvKsMKm_v51OrrzjIfY6I',
    appId: '1:585764705287:android:080721b528c83b7f3e06a2',
    messagingSenderId: '585764705287',
    projectId: 'flutterflix-375a9',
    storageBucket: 'flutterflix-375a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23QW01p-ql_2tEQrGDaV_h1Faf6qL_04',
    appId: '1:585764705287:ios:d6f743c86ff55a143e06a2',
    messagingSenderId: '585764705287',
    projectId: 'flutterflix-375a9',
    storageBucket: 'flutterflix-375a9.appspot.com',
    iosBundleId: 'com.example.flutflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD23QW01p-ql_2tEQrGDaV_h1Faf6qL_04',
    appId: '1:585764705287:ios:7372b2ffef2d45c73e06a2',
    messagingSenderId: '585764705287',
    projectId: 'flutterflix-375a9',
    storageBucket: 'flutterflix-375a9.appspot.com',
    iosBundleId: 'com.example.flutflix.RunnerTests',
  );
}
